server:
  port: 8081

spring:
  application:
    name: backend-bufete

  datasource:
    url: jdbc:postgresql://ep-curly-wave-ady17a0d-pooler.c-2.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_UPSVbM5tA2lL&sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_UPSVbM5tA2lL
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    logging:
      level:
        org.hibernate.type.descriptor.sql.BasicBinder: TRACE

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

aws:
  access-key: AKIAUULD6N3ICM6FNXNN
  secret-key: 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
  region: sa-east-1
  s3:
    bucket-name: bucketbufete
    base-path: documentos

logging:
  level:
    com.bufete: DEBUG
    org.springframework.web.multipart: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

app:
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  jwt-expiration-milliseconds: 1800000
